# Generated by Django 4.2.1 on 2023-05-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='4756Z', max_length=5, unique=True)),
                ('tonnage', models.PositiveSmallIntegerField(default=761)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
            ],
        ),
    ]
