# Generated by Django 4.2.1 on 2023-05-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('delivery_location', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_delivery_location', to='locations.location')),
                ('pickup_location', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_pickup_location', to='locations.location')),
            ],
        ),
    ]
