# Generated by Django 4.2.1 on 2023-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
