# Generated by Django 4.2.1 on 2023-05-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('cargo', '0002_alter_cargo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='delivery_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_delivery_location', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pickup_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_pickup_location', to='locations.location'),
        ),
    ]
